version: "3.9"
services:
  rabbitmqOtp:
    image: rabbitmq:3-management
    environment:
      - 'RABBITMQ_DEFAULT_PASS=guest'
      - 'RABBITMQ_DEFAULT_USER=guest'
    container_name: rabbitmqOtp
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
    ports:
      - "5432:5432"
  postgres2:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=root2
      - POSTGRES_PASSWORD=secret2
    ports:
      - "5433:5432"
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Admin123
    ports:
        - "27017:27017"
volumes:
  rabbitmq_data:

