spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: api-service
          predicates:
            - Path=/api-service/**
          uri: http://localhost:3000


  main:
    web-application-type: reactive

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#logging:
#  level:
#    org.springframework.web.HttpLogging: TRACE
#    reactor.netty.http.server: DEBUG
#    reactor.netty.http.client: DEBUG

server:
  port: 8080

authentication:
  enabled: false